# Generated by Django 3.0 on 2019-12-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='<Unknown>', max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'customer',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MixinRegularCustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_pet', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegularCustomer',
            fields=[
                ('mixinregularcustomerinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='face_detection.MixinRegularCustomerInfo')),
                ('name', models.CharField(default='<Unknown>', max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'regular_customer',
                'abstract': False,
            },
            bases=('face_detection.mixinregularcustomerinfo', models.Model),
        ),
    ]
