# Generated by Django 3.0 on 2019-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0003_auto_20191204_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_visit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of first visit'),
        ),
        migrations.AlterField(
            model_name='regularcustomer',
            name='first_visit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of first visit'),
        ),
    ]
