# Generated by Django 3.0 on 2019-12-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0004_auto_20191204_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_species',
            field=models.ManyToManyField(to='face_detection.Species'),
        ),
    ]
